wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689980411.879105
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      3:
      - 7
      - 19
      - 23
      4: 3.11.4
      5: 0.15.5
      6: 4.30.2
      8:
      - 3
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
batch_size:
  desc: null
  value: 4
config:
  desc: null
  value:
    seg_model: Unet
    encoder_name: timm-resnest26d
    loss_smooth: 1.0
    image_size: 512
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0
    scheduler:
      name: cosine_with_hard_restarts_schedule_with_warmup
      params:
        cosine_with_hard_restarts_schedule_with_warmup:
          num_warmup_steps: 350
          num_training_steps: 3150
          num_cycles: 1
