data_path: "D:/Machine_Learning/hubmap-hacking-the-human-vasculature/data"
output_dir: "D:/Machine_Learning/hubmap-hacking-the-human-vasculature/models/unetplusplus/version_0"

folds:
  n_splits: 5
  random_state: 42
train_folds: [0, 1, 2, 3, 4]

seed: 42

train_bs: 2
valid_bs: 2
workers: 1

progress_bar_refresh_rate: 1

early_stop:
  monitor: "val_loss"
  mode: "min"
  patience: 999
  verbose: 1

trainer:
  max_epochs: 1
  min_epochs: 1
  enable_progress_bar: True
  precision: "16-mixed"
  devices: 1

model:
  seg_model: "Unet++"
  encoder_name: "timm-resnest26d"
  loss_smooth: 1.0
  image_size: 512
  optimizer_params:
    lr: 0.0005
    weight_decay: 0.0
  scheduler:
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
      cosine_with_hard_restarts_schedule_with_warmup:
        num_warmup_steps: 350
        num_training_steps: 3150
        num_cycles: 1
