wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689979638.161463
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      3:
      - 7
      - 19
      - 23
      4: 3.11.4
      5: 0.15.5
      6: 4.30.2
      8:
      - 3
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
batch_size:
  desc: null
  value: 2
